# Generated by Django 5.2.7 on 2025-11-09 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='cargo_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('passage', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fragile', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_transit', 'В пути'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='delivery.cargotype')),
                ('from_container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='delivery.container')),
                ('to_container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='delivery.container')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
