# Generated by Django 5.2.7 on 2025-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='bazar',
        ),
        migrations.RemoveField(
            model_name='shipmentstop',
            name='container',
        ),
        migrations.RemoveField(
            model_name='courierposition',
            name='speed_kmh',
        ),
        migrations.AddField(
            model_name='shipmentstop',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Широта (lat)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentstop',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Долгота (lon)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentstop',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес / подпись'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bazar',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
