# Generated by Django 5.2.7 on 2025-11-12 00:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_bazar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Скорость, км/ч')),
                ('heading', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Градуч поворота, °')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Позиция курьера',
                'verbose_name_plural': 'Позиции курьеров',
            },
        ),
        migrations.CreateModel(
            name='CourierSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Посадка')),
                ('per_km_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за км')),
                ('min_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минималка')),
                ('fragile_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Хрупкость, %')),
                ('size_s_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='×S')),
                ('size_m_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='×M')),
                ('size_l_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.15'), max_digits=5, verbose_name='×L')),
            ],
            options={
                'verbose_name': 'Сегмент тарифа',
                'verbose_name_plural': 'Сегменты тарифа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='Bazar',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='cargo_type',
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['title'], 'verbose_name': 'Точка (контейнер)', 'verbose_name_plural': 'Точки (контейнеры)'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_container',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_container',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='user',
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_as_carrier', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_stop_index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Индекс цели'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Дистанция, км'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_fare',
            field=models.PositiveIntegerField(default=0, verbose_name='Предварительная стоимость'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='eta_to_next_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='ETA, мин'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='final_fare',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая стоимость'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='size',
            field=models.CharField(choices=[('S', 'Маленькая'), ('M', 'Средняя'), ('L', 'Большая')], default='M', max_length=1, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='title',
            field=models.CharField(default=1, max_length=155, verbose_name='Название посылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='container',
            name='passage',
            field=models.CharField(max_length=50, verbose_name='Проход'),
        ),
        migrations.AlterField(
            model_name='container',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fragile',
            field=models.BooleanField(default=False, verbose_name='Хрупкая'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('assigned', 'Назначен'), ('in_transit', 'В пути'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='segment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='delivery.couriersegment', verbose_name='Тариф'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentstop',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_stops', to='delivery.container', verbose_name='Точка'),
        ),
        migrations.AddField(
            model_name='shipmentstop',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.shipment', verbose_name='Посылка'),
        ),
        migrations.DeleteModel(
            name='CargoType',
        ),
        migrations.AlterUniqueTogether(
            name='shipmentstop',
            unique_together={('shipment', 'position')},
        ),
    ]
