# Generated by Django 5.2.7 on 2025-11-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_container_bazar_remove_shipmentstop_container_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='item_label',
        ),
    ]
