# Generated by Django 5.2.7 on 2025-11-12 10:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_courierposition_couriersegment_shipmentstop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Базар')),
            ],
            options={
                'verbose_name': 'Базар',
                'verbose_name_plural': 'Базары',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='couriersegment',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Сегмент тарифа', 'verbose_name_plural': 'Сегменты тарифа'},
        ),
        migrations.RemoveField(
            model_name='container',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='container',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='courierposition',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='courierposition',
            name='longitude',
        ),
        migrations.AddField(
            model_name='container',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=1, geography=True, srid=4326, verbose_name='Точка (lon, lat)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courierposition',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=1, geography=True, srid=4326, verbose_name='Точка (lon, lat)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couriersegment',
            name='icon',
            field=models.CharField(blank=True, max_length=64, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='couriersegment',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в UI'),
        ),
        migrations.AddField(
            model_name='couriersegment',
            name='per_unit',
            field=models.BooleanField(default=True, verbose_name='Цена за единицу'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='item_label',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тип груза (UI)'),
        ),
        migrations.AlterField(
            model_name='courierposition',
            name='heading',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс, °'),
        ),
        migrations.AddField(
            model_name='container',
            name='bazar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='delivery.bazar', verbose_name='Базар'),
            preserve_default=False,
        ),
    ]
