# Generated by Django 5.2.7 on 2025-11-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_shipment_item_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierposition',
            name='heading',
        ),
    ]
