# Generated by Django 5.2.7 on 2025-11-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_bazar_alter_couriersegment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='location',
        ),
        migrations.RemoveField(
            model_name='courierposition',
            name='location',
        ),
        migrations.AddField(
            model_name='container',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Широта (lat)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Долгота (lon)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courierposition',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Широта (lat)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courierposition',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Долгота (lon)'),
            preserve_default=False,
        ),
    ]
