# Generated by Django 5.2.7 on 2025-11-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_courierposition_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriersegment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='couriersegment',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
    ]
