# Generated by Django 5.2.7 on 2025-11-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_container_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentstop',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
    ]
