# Generated by Django 5.2.7 on 2025-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_couriersegment_description_alter_couriersegment_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
    ]
