# Generated by Django 5.2.7 on 2025-11-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_shipment_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='rating_applied',
            field=models.BooleanField(default=False, verbose_name='Рейтинг начислен'),
        ),
    ]
