# Generated by Django 5.2.7 on 2025-11-26 03:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_shipment_rating_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriersegment',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='couriersegment',
            name='fragile_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Наценка за хрупкость, %'),
        ),
        migrations.AlterField(
            model_name='couriersegment',
            name='size_l_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.15'), max_digits=5, verbose_name='Множитель для L (больш.)'),
        ),
        migrations.AlterField(
            model_name='couriersegment',
            name='size_m_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Множитель для M (сред.)'),
        ),
        migrations.AlterField(
            model_name='couriersegment',
            name='size_s_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Множитель для S (мал.)'),
        ),
    ]
