# Generated by Django 5.2.7 on 2025-12-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_couriersegment_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачено в'),
        ),
    ]
