# Generated by ChatGPT on 2026-01-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0009_shipment_is_paid_shipment_paid_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bazar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=155, unique=True, verbose_name="Базар")),
            ],
            options={
                "verbose_name": "Базар",
                "verbose_name_plural": "Базары",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Passage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=50, verbose_name="Проход")),
                (
                    "bazar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passages",
                        to="delivery.bazar",
                        verbose_name="Базар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проход",
                "verbose_name_plural": "Проходы",
                "ordering": ["bazar__name", "number"],
            },
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=50, verbose_name="Номер")),
                ("title", models.CharField(blank=True, max_length=150, verbose_name="Название")),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9, verbose_name="Широта (lat)")),
                ("lon", models.DecimalField(decimal_places=6, max_digits=9, verbose_name="Долгота (lon)")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "passage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="containers",
                        to="delivery.passage",
                        verbose_name="Проход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контейнер",
                "verbose_name_plural": "Контейнеры",
                "ordering": ["passage__bazar__name", "passage__number", "number"],
            },
        ),
        migrations.AddConstraint(
            model_name="passage",
            constraint=models.UniqueConstraint(fields=("bazar", "number"), name="uniq_passage_bazar_number"),
        ),
        migrations.AddConstraint(
            model_name="container",
            constraint=models.UniqueConstraint(fields=("passage", "number"), name="uniq_container_passage_number"),
        ),
        migrations.AddField(
            model_name="shipmentstop",
            name="container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_stops",
                to="delivery.container",
                verbose_name="Контейнер",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentstop",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес / подпись"),
        ),
        migrations.AlterField(
            model_name="shipmentstop",
            name="lat",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Широта (lat)"),
        ),
        migrations.AlterField(
            model_name="shipmentstop",
            name="lon",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Долгота (lon)"),
        ),
    ]
