# Generated by Django 5.2.7 on 2026-04-11 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_bazar_passage_container_and_stop_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couriersegment',
            name='fragile_pct',
        ),
        migrations.RemoveField(
            model_name='couriersegment',
            name='per_unit',
        ),
        migrations.RemoveField(
            model_name='couriersegment',
            name='size_l_multiplier',
        ),
        migrations.RemoveField(
            model_name='couriersegment',
            name='size_m_multiplier',
        ),
        migrations.RemoveField(
            model_name='couriersegment',
            name='size_s_multiplier',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='fragile',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='size',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='delivery.couriersegment', verbose_name='Тариф'),
        ),
    ]
