# Generated by Django 5.2.7 on 2026-04-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_remove_couriersegment_fragile_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='segment',
        ),
        migrations.DeleteModel(
            name='CourierSegment',
        ),
    ]
