# Generated by Django 5.2.7 on 2026-04-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_remove_shipment_segment_delete_couriersegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDeliveryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Базовая стоимость')),
                ('per_km_price', models.DecimalField(decimal_places=2, default=20, max_digits=10, verbose_name='Стоимость за км')),
                ('min_fare', models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Минималка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Глобальные настройки цен',
                'verbose_name_plural': 'Глобальные настройки цен',
            },
        ),
    ]
