# Generated by Django 5.2.7 on 2026-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_globaldeliveryconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazar',
            name='coordinates',
            field=models.JSONField(blank=True, null=True, verbose_name='Координаты области (GeoJSON/Список)'),
        ),
        migrations.AddField(
            model_name='bazar',
            name='price_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='bazar',
            name='price_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена до'),
        ),
    ]
