# Generated by Django 5.2.7 on 2026-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_bazar_coordinates_bazar_price_from_bazar_price_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazar',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='bazar',
            name='bottom_right_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта (низ-право)'),
        ),
        migrations.AddField(
            model_name='bazar',
            name='bottom_right_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота (низ-право)'),
        ),
        migrations.AddField(
            model_name='bazar',
            name='top_left_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта (верх-лево)'),
        ),
        migrations.AddField(
            model_name='bazar',
            name='top_left_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота (верх-лево)'),
        ),
    ]
