# Generated by Codex on 2026-08-03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0017_market_map_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketBoundaryMapSection",
            fields=[],
            options={
                "verbose_name": "Карта: граница базара",
                "verbose_name_plural": "Карта: границы базаров",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("delivery.marketmaprevision",),
        ),
        migrations.CreateModel(
            name="MarketPassageMapSection",
            fields=[],
            options={
                "verbose_name": "Карта: проход",
                "verbose_name_plural": "Карта: проходы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("delivery.marketmaprevision",),
        ),
        migrations.CreateModel(
            name="MarketContainerMapSection",
            fields=[],
            options={
                "verbose_name": "Карта: контейнер",
                "verbose_name_plural": "Карта: контейнеры",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("delivery.marketmaprevision",),
        ),
    ]
