# Generated by Django 5.2.7 on 2026-08-04 07:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_amanat(apps, schema_editor):
    AmanatCategory = apps.get_model('delivery', 'AmanatCategory')
    AmanatCampaign = apps.get_model('delivery', 'AmanatCampaign')

    categories = [
        ('Все', 'all', 0, False),
        ('Детям', 'children', 10, True),
        ('Лечение', 'treatment', 20, True),
        ('Помощь семьям', 'families', 30, True),
        ('Образование', 'education', 40, True),
        ('Другое', 'other', 50, True),
    ]
    created = {}
    for name, slug, sort_order, is_active in categories:
        obj, _ = AmanatCategory.objects.update_or_create(
            slug=slug,
            defaults={'name': name, 'sort_order': sort_order, 'is_active': is_active},
        )
        created[slug] = obj

    if not AmanatCampaign.objects.exists():
        AmanatCampaign.objects.create(
            category=created['children'],
            title='Айдане на операцию',
            short_title='Поможем Айдане\nна операцию',
            description='Айдане требуется операция и постоянное наблюдение врачей. Сбор открыт для оплаты лечения, дороги и необходимых медицинских расходов семьи.',
            goal='Собрать средства на операцию и послеоперационный уход.',
            needed_amount=1600000,
            collected_amount_manual=650000,
            safa_amount=706624,
            helpers_count_manual=842,
            ends_at='2026-05-30',
            is_featured=True,
            sort_order=0,
            status='active',
        )
        AmanatCampaign.objects.create(
            category=created['treatment'],
            title='Тимуру на лечение',
            short_title='Поможем Тимуру\nна лечение',
            description='Тимуру нужна срочная операция и курс восстановления. Семья уже собрала часть суммы самостоятельно, но оставшаяся сумма пока недоступна.',
            goal='Оплатить операцию, лекарства и первые недели реабилитации.',
            needed_amount=840000,
            collected_amount_manual=650000,
            safa_amount=0,
            helpers_count_manual=128,
            ends_at='2026-05-30',
            sort_order=10,
            status='active',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_market_map_section_proxies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmanatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='Slug')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Аманат категория',
                'verbose_name_plural': 'Аманат категории',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AmanatCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('short_title', models.CharField(blank=True, max_length=180, verbose_name='Короткое название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('goal', models.CharField(blank=True, max_length=255, verbose_name='Цель')),
                ('needed_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Нужно собрать')),
                ('collected_amount_manual', models.PositiveIntegerField(default=0, verbose_name='Собрано вручную')),
                ('safa_amount', models.PositiveIntegerField(default=0, verbose_name='Начисления Safa')),
                ('helpers_count_manual', models.PositiveIntegerField(default=0, verbose_name='Помогли вручную')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='amanat/campaigns/', verbose_name='Фото')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('completed', 'Завершён'), ('canceled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Главный сбор')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='delivery.amanatcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Аманат сбор',
                'verbose_name_plural': 'Аманат сборы',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AmanatDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_label', models.CharField(blank=True, max_length=120, verbose_name='Имя/телефон для отображения')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачено'), ('failed', 'Ошибка'), ('canceled', 'Отменено')], default='paid', max_length=20, verbose_name='Статус')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимно')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено в')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='delivery.amanatcampaign', verbose_name='Сбор')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amanat_donations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аманат пожертвование',
                'verbose_name_plural': 'Аманат пожертвования',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(seed_amanat, migrations.RunPython.noop),
    ]
