# Generated by Django 5.2.7 on 2026-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_amanatcategory_amanatcampaign_amanatdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazar',
            name='district',
            field=models.CharField(blank=True, max_length=155, verbose_name='Район'),
        ),
    ]
