# Generated by Django 5.2.7 on 2026-08-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_bazar_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDistrictMapSection',
            fields=[
            ],
            options={
                'verbose_name': 'Карта: район базара',
                'verbose_name_plural': 'Карта: районы базаров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('delivery.marketmaprevision',),
        ),
    ]
