# Generated by Django 5.2.7 on 2026-08-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_marketdistrictmapsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdistrictmapsection',
            options={'verbose_name': 'Карта: граница района', 'verbose_name_plural': 'Карта: границы районов'},
        ),
    ]
