# Generated by Django 5.2.7 on 2026-08-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_alter_shipmentstop_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='work_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Работа выполнена специалистом'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('assigned', 'Назначен'), ('in_transit', 'В пути'), ('awaiting_payment', 'Ожидает оплаты'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
