# Generated by Django 5.2.7 on 2026-08-11 09:28

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def reopen_unpaid_completed_shipments(apps, schema_editor):
    Shipment = apps.get_model("delivery", "Shipment")
    for shipment in Shipment.objects.filter(status="completed", is_paid=False):
        fare = int(shipment.final_fare or shipment.estimated_fare or 0)
        if shipment.carrier_id and fare > 0:
            shipment.status = "awaiting_payment"
            shipment.final_fare = fare
            shipment.work_completed_at = (
                shipment.work_completed_at
                or shipment.finished_at
                or timezone.now()
            )
            shipment.finished_at = None
            shipment.save(
                update_fields=[
                    "status",
                    "final_fare",
                    "work_completed_at",
                    "finished_at",
                ]
            )
        else:
            shipment.status = "canceled"
            shipment.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_shipment_work_completed_at_alter_shipment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            reopen_unpaid_completed_shipments,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('is_paid', True), _connector='OR'), name='delivery_completed_requires_payment'),
        ),
    ]
