# Generated by Django 5.2.7 on 2026-08-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_shipment_delivery_completed_requires_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amanatdonation',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачено'), ('failed', 'Ошибка'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
