# Generated by Django 5.2.7 on 2026-08-24 17:13

from django.db import migrations, models


def backfill_passage_districts(apps, schema_editor):
    """Проставляет район уже существующим проходам по опубликованной карте.

    Раньше проход не знал своего района, поэтому у всех старых записей район
    пустой. Уникальность это не ломает (номера были уникальны на весь базар),
    но без района проход из района А и проход из района Б неразличимы.
    """
    from apps.delivery.map_validation import district_name_for_geometry, iter_district_features

    Passage = apps.get_model("delivery", "Passage")
    MarketMapRevision = apps.get_model("delivery", "MarketMapRevision")

    revisions = MarketMapRevision.objects.order_by("bazar_id", "-version")
    seen: set[int] = set()
    updated = []
    for revision in revisions:
        if revision.bazar_id in seen:
            continue
        seen.add(revision.bazar_id)

        geojson = revision.geojson if isinstance(revision.geojson, dict) else {}
        districts = iter_district_features(geojson)
        if not districts:
            continue

        by_id = {
            passage.id: passage
            for passage in Passage.objects.filter(bazar_id=revision.bazar_id)
        }
        for feature in geojson.get("features") or []:
            properties = (feature or {}).get("properties") or {}
            if properties.get("kind") != "passage":
                continue
            passage = by_id.get(properties.get("passage_id"))
            if passage is None or passage.district:
                continue
            district = district_name_for_geometry(feature.get("geometry") or {}, districts)
            if district:
                passage.district = district
                updated.append(passage)

    if updated:
        Passage.objects.bulk_update(updated, ["district"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0030_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['bazar__name', 'district', 'number'], 'verbose_name': 'Проход', 'verbose_name_plural': 'Проходы'},
        ),
        migrations.RemoveConstraint(
            model_name='passage',
            name='uniq_passage_bazar_number',
        ),
        migrations.AddField(
            model_name='passage',
            name='district',
            field=models.CharField(blank=True, max_length=155, verbose_name='Район'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.UniqueConstraint(fields=('bazar', 'district', 'number'), name='uniq_passage_bazar_district_number'),
        ),
        migrations.RunPython(backfill_passage_districts, migrations.RunPython.noop),
    ]
