# Generated by Django 5.2.7 on 2026-08-24 17:34

from django.db import migrations, models


def backfill_passage_angles(apps, schema_editor):
    """Считает угол наклона уже нарисованным проходам по последней карте."""
    from apps.delivery.map_validation import passage_angle_for_geometry

    Passage = apps.get_model("delivery", "Passage")
    MarketMapRevision = apps.get_model("delivery", "MarketMapRevision")

    seen: set[int] = set()
    updated = []
    for revision in MarketMapRevision.objects.order_by("bazar_id", "-version"):
        if revision.bazar_id in seen:
            continue
        seen.add(revision.bazar_id)

        geojson = revision.geojson if isinstance(revision.geojson, dict) else {}
        by_id = {
            passage.id: passage
            for passage in Passage.objects.filter(bazar_id=revision.bazar_id)
        }
        for feature in geojson.get("features") or []:
            properties = (feature or {}).get("properties") or {}
            if properties.get("kind") != "passage":
                continue
            passage = by_id.get(properties.get("passage_id"))
            if passage is None or passage.angle is not None:
                continue
            angle = passage_angle_for_geometry(feature.get("geometry") or {})
            if angle is not None:
                passage.angle = angle
                updated.append(passage)

    if updated:
        Passage.objects.bulk_update(updated, ["angle"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0031_passage_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='angle',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Угол наклона, °'),
        ),
        migrations.RunPython(backfill_passage_angles, migrations.RunPython.noop),
    ]
