# Generated by Django 5.2.7 on 2026-08-29 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0033_sync_map_district_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmanatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='amanat/documents/', verbose_name='Файл документа (PDF, изображение, скан)')),
                ('description', models.TextField(blank=True, verbose_name='Описание / примечание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='delivery.amanatcampaign', verbose_name='Сбор')),
            ],
            options={
                'verbose_name': 'Отчётный документ',
                'verbose_name_plural': 'Отчётные документы',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
