# Generated by Django 5.2.7 on 2026-08-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0034_amanatdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+996 509 10 67 88', max_length=50, verbose_name='Телефон поддержки')),
                ('telegram', models.CharField(default='996509106788', max_length=100, verbose_name='Telegram (username или телефон)')),
                ('whatsapp', models.CharField(blank=True, default='+996509106788', max_length=50, verbose_name='WhatsApp')),
                ('working_hours', models.CharField(default='Ежедневно с 09:00 до 21:00 по Бишкеку.', max_length=255, verbose_name='Часы работы')),
                ('message', models.TextField(default='Если что-то пошло не так — напишите нам или позвоните. Мы поможем с заказами, оплатой и приложением.', verbose_name='Текст сообщения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Служба поддержки',
                'verbose_name_plural': 'Служба поддержки',
            },
        ),
    ]
