# Generated by Django 5.2.7 on 2026-08-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0035_supportcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Частый вопрос (FAQ)',
                'verbose_name_plural': 'Частые вопросы (FAQ)',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='1. Какие данные мы собираем\nМы собираем данные, необходимые для работы сервиса доставки: ваше имя, номер телефона, данные о местоположении для отслеживания посылок в реальном времени, а также информацию о ваших заказах.\n\n2. Как мы используем данные\nВаше местоположение используется для построения маршрута курьером и информирования клиента о статусе доставки. Номер телефона необходим для связи и подтверждения заказов.\n\n3. Передача данных третьим лицам\nМы не продаём ваши данные. Данные передаются только участникам процесса доставки (курьеру или клиенту) исключительно для выполнения услуги.\n\n4. Безопасность\nМы используем современные методы шифрования для защиты вашей личной информации и данных о платежах.\n\n5. Ваши права\nВы имеете право запросить удаление вашего аккаунта и всех связанных данных в любой момент через службу поддержки.', verbose_name='Текст политики конфиденциальности')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
    ]
