upstream django {
    server web:8000;
}

# HTTP → редирект на HTTPS + поддержка certbot
server {
    listen 80;
    server_name dordoi-go.tech www.dordoi-go.tech;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS — основной сервер
server {
    listen 443 ssl;
    server_name dordoi-go.tech www.dordoi-go.tech;

    ssl_certificate     /etc/letsencrypt/live/dordoi-go.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dordoi-go.tech/privkey.pem;

    charset utf-8;
    client_max_body_size 20M;

    location /static/ {
        alias /app/static_root/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        proxy_pass http://django;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
