# Generated by Django 5.2.7 on 2025-12-21 21:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0009_shipment_is_paid_shipment_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('FINIK', 'Finik')], default='FINIK', max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='KGS', max_length=8)),
                ('finik_request_id', models.CharField(max_length=64, unique=True)),
                ('finik_transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('finik_item_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('raw_callback_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='delivery.shipment')),
            ],
            options={
                'indexes': [models.Index(fields=['shipment', 'status'], name='payments_pa_shipmen_de05ba_idx'), models.Index(fields=['finik_request_id'], name='payments_pa_finik_r_debde0_idx')],
            },
        ),
    ]
