# Generated by Django 5.2.7 on 2025-12-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentattempt',
            name='payments_pa_shipmen_de05ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentattempt',
            name='payments_pa_finik_r_debde0_idx',
        ),
    ]
