# Generated by Django 5.2.7 on 2026-08-11 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_shipment_work_completed_at_alter_shipment_status'),
        ('payments', '0003_alter_paymentattempt_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.PositiveIntegerField()),
                ('commission_amount', models.PositiveIntegerField()),
                ('net_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='KGS', max_length=8)),
                ('status', models.CharField(choices=[('CREDITED', 'Начислено')], default='CREDITED', max_length=16)),
                ('credited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_settlements', to=settings.AUTH_USER_MODEL)),
                ('payment_attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_settlement', to='payments.paymentattempt')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_settlement', to='delivery.shipment')),
            ],
            options={
                'ordering': ('-credited_at',),
            },
        ),
    ]
