# Generated by Django 5.2.7 on 2026-08-12 07:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_shipment_delivery_completed_requires_payment'),
        ('payments', '0004_carriersettlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmanatPaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('FINIK', 'Finik')], default='FINIK', max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='KGS', max_length=8)),
                ('finik_request_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('finik_transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('finik_item_id', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_callback_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempt', to='delivery.amanatdonation')),
            ],
        ),
    ]
