# Generated by Django 5.2.7 on 2025-11-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('carrier', 'Тачкист'), ('client', 'Клиент')], default='client', max_length=16),
        ),
    ]
