# Generated by Django 5.2.7 on 2025-11-10 21:41

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierkyc',
            name='selfie_id_card',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.kyc_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Формат телефона: 996XXXXXXXXX (Кыргызстан).', regex='^996\\d{9}$')]),
        ),
    ]
