# Generated by Django 5.2.7 on 2025-11-11 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_courierkyc_selfie_id_card_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CarrierProfile',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
