# Generated by Django 5.2.7 on 2025-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Город'),
        ),
    ]
