# Generated by Django 5.2.7 on 2025-11-25 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=django.core.validators.MaxValueValidator(100)),
        ),
    ]
