# Generated by Django 5.2.7 on 2025-11-25 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rate',
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка'),
        ),
    ]
