# Generated by Django 5.2.7 on 2025-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_rate_userprofile_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='client_rate_count',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Сколько клиентов оценили'),
        ),
    ]
