# Generated by Django 5.2.7 on 2025-11-26 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('client', 'Клиентское приложение'), ('carrier', 'Курьерское приложение')], max_length=16, verbose_name='Приложение')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('channel', models.CharField(choices=[('orders', 'Заказы'), ('system', 'Системные')], default='system', max_length=32, verbose_name='Канал')),
                ('deep_link', models.CharField(blank=True, max_length=255, verbose_name='Deep-link (опционально)')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные (словарь в data-payload)')),
                ('silent', models.BooleanField(default=False, verbose_name='Тихое уведомление (data-only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Ручное уведомление',
                'verbose_name_plural': 'Ручные уведомления',
            },
        ),
    ]
