# Generated by Django 5.2.7 on 2025-11-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('app', models.CharField(choices=[('client', 'Клиентское приложение'), ('carrier', 'Курьерское приложение')], max_length=20, verbose_name='Приложение')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('carrier', 'Курьер')], max_length=20, verbose_name='Роль получателей')),
                ('channel', models.CharField(default='system', max_length=50, verbose_name='Канал')),
                ('deep_link', models.CharField(blank=True, max_length=255, verbose_name='Deep-link')),
                ('silent', models.BooleanField(default=False, verbose_name='Тихое уведомление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Сколько юзеров получили')),
            ],
            options={
                'verbose_name': 'Рассылка по роли',
                'verbose_name_plural': 'Рассылки по роли',
            },
        ),
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
